version: '3.8'

services:
  backend:
    build: ./backend
    container_name: flask-backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    depends_on:
      - redis

  frontend:
    build: ./frontend
    container_name: vue-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

  redis:
    image: redis:alpine
    container_name: flask-redis
    ports:
      - "6379:6379"